name: Documentation

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - update-docs*

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels defaults
    - name: Install dependencies
      run: |
        conda install -y python=3.12
        conda env update --file docs-environment.yml --name base
    - name: Build documentation
      run: |
        python --version
        python build_docs.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
  