name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
      - 'testv*'

jobs:
  release-build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: build a binary wheel and a source tarball
        run: |
          python -m pip install build
          python -m build

      - name: upload distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

# For a full release, publish to PyPI and create a GitHub release
  pypi-publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/v')  # publish to PyPI on tag pushes starting with 'v'
    runs-on: ubuntu-latest
    needs:
      - release-build

    environment:
      name: pypi
      url: https://pypi.org/p/qucat
    permissions:
      id-token: write
      contents: write

    steps:
      - name: download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

# For a pre-release, publish to TestPyPI and create a GitHub pre-release
  publish-to-testpypi:
    name: Publish to TestPyPI if tagged
    if: startsWith(github.ref, 'refs/tags/testv')  # publish to testPyPI on tag pushes starting with 'testv'
    runs-on: ubuntu-latest
    needs:
      - release-build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/test-qucat
    permissions:
      id-token: write
      contents: write

    steps:
      - name: download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Create GitHub Pre-release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          generateReleaseNotes: true
