name: Build status

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        ## os: [ubuntu-latest, macOS-12, windows-latest]
        os: [windows-latest]
        ## python-version: ["3.7", "3.10", "3.11", "3.12"]
        python-version: ["3.10"]
        exclude:
          - os: macOS-12
            python-version: "3.7"
          - os: windows-latest
            python-version: "3.7"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      shell: bash
      run: |
        ls -l $CONDA/condabin/conda.bat
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        # echo $CONDA/bin >> $GITHUB_PATH
        # echo $CONDA
    - name: Install dependencies
      shell: bash
      run: |
        $CONDA/condabin/conda.bat env update --file test-environment.yml --name base
    - name: Test with pytest
      shell: bash
      run: |
        # avoid tkinter error
        # See https://github.com/orgs/community/discussions/62479
        # export DISPLAY=:99
        # Xvfb :99 &
        pytest --cov=src
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      if: |
        ${{ matrix.python-version == '3.12' }} &&
        ${{ matrix.os == 'ubuntu-latest' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
