name: Build status

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels defaults
    - name: Install dependencies
      run: |
        conda install -y python=${{ matrix.python-version }}
        conda env update --file test-environment.yml --name base
    - name: Test with pytest
      run: |
        # avoid tkinter error
        # See https://github.com/orgs/community/discussions/62479
        export DISPLAY=:99
        Xvfb :99 &
        python --version
        pytest --cov=src
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      if: |
        ${{ matrix.python-version == '3.12' }} &&
        ${{ matrix.os == 'ubuntu-latest' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
