name: Build status

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      # read this: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#using-multiple-python-versions

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file test-environment.yml --name base
    - name: Test with pytest
      run: |
        # avoid tkinter error
        # See https://github.com/orgs/community/discussions/62479
        export DISPLAY=:99
        Xvfb :99 &
        pytest --cov=src
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
