name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      # read this: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#using-multiple-python-versions

    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        options: "--check --verbose --line-length=79"
        jupyter: true
        version: "22.10.0"
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        # conda env update --file environment.yml --name base
        conda install nbdime conda-forge::qutip
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install pytest
    - name: Test with pytest
      run: |
        # avoid tkinter error
        # See https://github.com/orgs/community/discussions/62479
        export DISPLAY=:99
        Xvfb :99 &
        pytest
